services:
  postgres:
    image: 'postgres:17'
    environment:
      - 'POSTGRES_DB=icglma_local'
      - 'POSTGRES_PASSWORD=ICGLMA@2025'
      - 'POSTGRES_USER=icglma'
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: