spring.application.name=incident-management-system

### PostgreSQL

spring.datasource.url=jdbc:postgresql://localhost:5432/icglma_local
spring.datasource.username=icglma
spring.datasource.password=ICGLMA@2025

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

### JWT configuration used for signing tokens
jwt.secret=1cx3NyULn6FPy3ir6JDZ5o392y3LSm1H

### token validity in milliseconds (43200000 = 12 hours)
jwt.expiration-ms=43200000

### refresh token validity in milliseconds (604800000 = 7 days)
jwt.refresh-expiration-ms=604800000