spring.application.name=incident-management-system

### PostgreSQL ###
spring.datasource.url=jdbc:postgresql://localhost:5432/icglma_local
spring.datasource.username=icglma
spring.datasource.password=ICGLMA@2025

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect