package incident.management.system.idempotency;

import incident.management.system.exception.IdempotencyConflictException;
import incident.management.system.exception.MissingIdempotencyKeyException;
import lombok.extern.slf4j.Slf4j;
import org.aspectj.lang.ProceedingJoinPoint;
import org.aspectj.lang.annotation.Around;
import org.aspectj.lang.annotation.Aspect;
import org.aspectj.lang.reflect.MethodSignature;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.data.redis.core.StringRedisTemplate;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Component;
import org.springframework.util.StringUtils;
import org.springframework.web.context.request.RequestContextHolder;
import org.springframework.web.context.request.ServletRequestAttributes;
import tools.jackson.databind.JavaType;
import tools.jackson.databind.ObjectMapper;

import java.lang.reflect.Type;
import java.time.Duration;
import java.util.List;

/**
 * Distributed double-submit protection for {@link Idempotent}-annotated
 * endpoints (operators tapping "Déclarer" repeatedly over flaky factory Wi-Fi
 * previously created duplicate incidents).
 *
 * <p><b>Protocol</b> (all state lives in Redis — shared across instances):
 * <ol>
 *   <li>Read {@code X-Idempotency-Key} (a per-attempt UUID generated by the client).</li>
 *   <li>Atomic lock: {@code SETNX idempotency:{key}} with a TTL
 *       ({@value Idempotent#ttlSeconds} seconds default). If the lock is taken,
 *       this is the first attempt — proceed.</li>
 *   <li>If the lock already exists: replay the cached JSON response stored
 *       under {@code idempotency:{key}:response} (seamless recovery after a
 *       client-side timeout), or reject with {@code 409 Conflict} while the
 *       first attempt is still in flight.</li>
 *   <li>On success the response is cached under the same TTL. On failure the
 *       lock is released so the operator can retry with the same key.</li>
 * </ol>
 *
 * <p>Anti-patterns enforced: every key carries an explicit TTL (no unlimited
 * keys), the lock acquisition is atomic (no race between two parallel taps),
 * and no in-memory fallback exists.
 */
@Aspect
@Component
@Slf4j
public class IdempotencyAspect {

    public static final String KEY_PREFIX = "idempotency:";
    public static final String RESPONSE_SUFFIX = ":response";

    private final StringRedisTemplate redisTemplate;
    private final ObjectMapper objectMapper;

    @Value("${app.idempotency.ttl-seconds:30}")
    private long configuredTtlSeconds;

    public IdempotencyAspect(StringRedisTemplate redisTemplate, ObjectMapper objectMapper) {
        this.redisTemplate = redisTemplate;
        this.objectMapper = objectMapper;
    }

    @Around(value = "@annotation(idempotent)", argNames = "pjp,idempotent")
    public Object enforceIdempotency(ProceedingJoinPoint pjp, Idempotent idempotent) throws Throwable {
        String keyValue = currentRequestHeader(idempotent.headerName());

        if (!StringUtils.hasText(keyValue)) {
            if (idempotent.required()) {
                throw new MissingIdempotencyKeyException(idempotent.headerName());
            }
            // Optional dedup — no header, no protection needed for this request.
            return pjp.proceed();
        }

        long ttlSeconds = idempotent.ttlSeconds() > 0 ? idempotent.ttlSeconds() : configuredTtlSeconds;
        String lockKey = KEY_PREFIX + keyValue;
        String responseKey = lockKey + RESPONSE_SUFFIX;

        Boolean acquired = redisTemplate.opsForValue()
                .setIfAbsent(lockKey, "IN_PROGRESS", Duration.ofSeconds(ttlSeconds));

        if (!Boolean.TRUE.equals(acquired)) {
            // Duplicate submission inside the dedup window.
            Object cached = redisTemplate.opsForValue().get(responseKey);
            if (cached instanceof String cachedJson && StringUtils.hasText(cachedJson)) {
                log.debug("Replaying cached idempotent response for key '{}'", keyValue);
                return deserializeResponse(pjp, cachedJson);
            }
            log.warn("Duplicate idempotent request '{}' rejected (first attempt still in flight)", keyValue);
            throw new IdempotencyConflictException(keyValue);
        }

        try {
            Object result = pjp.proceed();
            cacheResponse(pjp, responseKey, result, ttlSeconds, keyValue);
            return result;
        } catch (Throwable t) {
            // Release the lock so a retry with the same key can succeed.
            try {
                redisTemplate.delete(List.of(lockKey, responseKey));
            } catch (Exception cleanupError) {
                log.warn("Failed to release idempotency lock '{}' after error", keyValue, cleanupError);
            }
            throw t;
        }
    }

    // ──────────────────────────────────────────────────────────────────────

    private void cacheResponse(ProceedingJoinPoint pjp, String responseKey,
                               Object result, long ttlSeconds, String keyValue) {
        // Cache the payload only — a ResponseEntity envelope (headers/status) is
        // not JSON-reconstructible and carries nothing the client needs on replay.
        Object toCache = unwrapResponseEntity(result);
        if (toCache == null) {
            return; // Void endpoint or empty body — nothing meaningful to replay.
        }
        try {
            String json = objectMapper.writeValueAsString(toCache);
            redisTemplate.opsForValue().set(responseKey, json, Duration.ofSeconds(ttlSeconds));
        } catch (Exception e) {
            // The write already succeeded — a failed cache write must not fail the request.
            log.warn("Could not cache idempotent response for key '{}'", keyValue, e);
        }
    }

    private Object deserializeResponse(ProceedingJoinPoint pjp, String cachedJson) {
        MethodSignature signature = (MethodSignature) pjp.getSignature();
        Type returnType = signature.getMethod().getGenericReturnType();
        try {
            JavaType javaType = objectMapper.constructType(returnType);
            if (javaType.getRawClass() == ResponseEntity.class && javaType.containedTypeCount() == 1) {
                // Method returns ResponseEntity<T> — rebuild the envelope around the
                // cached body. OK is used because the exact status (201 vs 200) does
                // not matter on a replay; the client only distinguishes success.
                Object body = objectMapper.readValue(cachedJson, javaType.containedType(0));
                return ResponseEntity.status(HttpStatus.OK).body(body);
            }
            return objectMapper.readValue(cachedJson, javaType);
        } catch (Exception e) {
            // Corrupt/stale cache entry — fail closed rather than replay garbage.
            throw new IdempotencyConflictException(null);
        }
    }

    private static Object unwrapResponseEntity(Object result) {
        if (result instanceof ResponseEntity<?> entity) {
            return entity.getBody();
        }
        return result;
    }

    private String currentRequestHeader(String headerName) {
        ServletRequestAttributes attributes =
                (ServletRequestAttributes) RequestContextHolder.getRequestAttributes();
        if (attributes == null) {
            return null;
        }
        return attributes.getRequest().getHeader(headerName);
    }
}
